from PyQt5 import QtCore, QtGui, QtWidgets

class CompanyUI(object):
    def setupUi(self, CompanyUI):
        CompanyUI.setObjectName("CompanyUI")
        CompanyUI.resize(800, 627)
        self.centralwidget = QtWidgets.QWidget(CompanyUI)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 100, 700, 450))
        self.pginfo = QtWidgets.QWidget()
        self.pginfo.setObjectName("pginfo")
        self.layoutWidget = QtWidgets.QWidget(self.pginfo)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 20, 350, 150))
        self.layoutWidget.setObjectName("layoutWidget")
        self.pg_trans = QtWidgets.QWidget()
        self.layoutWidget1 = QtWidgets.QWidget(self.pg_trans)
        self.layoutWidget1.setGeometry(QtCore.QRect(150, 180, 370, 120))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.linetransamt = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lbdate = QtWidgets.QLabel(self.layoutWidget)
        self.lbdate.setObjectName("lbdate")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(40)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.linebasicbal = QtWidgets.QLineEdit(self.layoutWidget)
        self.linebasicbal.setReadOnly(True)
        self.linebasicbal.setObjectName("linebasicbal")
        self.lbtotall = QtWidgets.QLabel(self.layoutWidget)
        self.lbtotall.setObjectName("lbtotall")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbtotall)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit.setReadOnly(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.tableinfobor = QtWidgets.QTableWidget(self.pginfo)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.lb_balance = QtWidgets.QLabel(self.layoutWidget)
        self.lb_balance.setObjectName("lb_balance")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_balance)
        self.tableinfobor.setGeometry(QtCore.QRect(60, 200, 550, 90))
        self.tableinfobor.setObjectName("tableinfobor")
        self.tableinfobor.setColumnCount(0)
        self.tableinfobor.setRowCount(0)
        self.formLayout2 = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout2.setContentsMargins(0, 0, 0, 0)
        self.formLayout2.setObjectName("formLayout2")
        self.lb_from_trans = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_from_trans.setObjectName("lb_from_trans")
        self.formLayout2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_from_trans)
        self.line_trans_from = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_trans_from.setObjectName("line_trans_from")
        self.lbamounttrans = QtWidgets.QLabel(self.layoutWidget1)
        self.lbamounttrans.setObjectName("lbamounttrans")
        self.lb_total_b = QtWidgets.QLabel(self.layoutWidget)
        self.formLayout2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbamounttrans)
        self.btnsubmittrans = QtWidgets.QPushButton(self.pg_trans)
        self.btnsubmittrans.setGeometry(QtCore.QRect(200, 350, 100, 30))
        self.btnsubmittrans.setObjectName("btnsubmittrans")
        self.btnresettrans = QtWidgets.QPushButton(self.pg_trans)
        self.btnresettrans.setGeometry(QtCore.QRect(350, 350, 90, 30))
        self.linetransamt.setObjectName("linetransamt")
        self.linebasiclent = QtWidgets.QLineEdit(self.layoutWidget)
        self.linebasiclent.setReadOnly(True)
        self.linebasiclent.setObjectName("linebasiclent")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.linebasiclent)
        self.tableinfolent = QtWidgets.QTableWidget(self.pginfo)
        self.tableinfolent.setGeometry(QtCore.QRect(60, 320, 550, 100))
        self.tableinfolent.setObjectName("tableinfolent")
        self.tableinfolent.setColumnCount(0)
        self.tableinfolent.setRowCount(0)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_total_b)
        self.linebasicborr = QtWidgets.QLineEdit(self.layoutWidget)
        self.linebasicborr.setReadOnly(True)
        self.linebasicborr.setObjectName("linebasicborr")
        self.lb_borrowed = QtWidgets.QLabel(self.pginfo)
        self.lb_borrowed.setGeometry(QtCore.QRect(300, 200, 70, 20))
        self.lb_borrowed.setObjectName("lb_borrowed")
        self.stackedWidget.setObjectName("stackedWidget")
        self.lblent = QtWidgets.QLabel(self.pginfo)
        self.lblent.setGeometry(QtCore.QRect(300, 300, 30, 20))
        self.lblent.setObjectName("lblent")
        self.stackedWidget.addWidget(self.pginfo)
        self.pg_trans.setObjectName("pg_trans")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbdate)
        self.formLayout2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.linetransamt)
        self.lbdatetrans = QtWidgets.QLabel(self.layoutWidget1)
        self.lbdatetrans.setObjectName("lbdatetrans")
        self.formLayout2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbdatetrans)
        self.transferdate = QtWidgets.QDateTimeEdit(self.layoutWidget1)
        self.transferdate.setReadOnly(False)
        self.transferdate.setObjectName("transferdate")
        self.formLayout2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.transferdate)
        self.tabletranslent = QtWidgets.QTableWidget(self.pg_trans)
        self.tabletranslent.setGeometry(QtCore.QRect(150, 60, 370, 90))
        self.tabletranslent.setObjectName("tabletranslent")
        self.btnresettrans.setObjectName("btnresettrans")
        self.tabletranslent.setColumnCount(0)
        self.lbborrowedtrans = QtWidgets.QLabel(self.pg_trans)
        self.lbborrowedtrans.setGeometry(QtCore.QRect(300, 30, 200, 30))
        self.lbborrowedtrans.setObjectName("lbborrowedtrans")
        self.tabletranslent.setRowCount(0)
        self.stackedWidget.addWidget(self.pg_trans)
        self.pgpur = QtWidgets.QWidget()
        self.pgpur.setObjectName("pgpur")
        self.label2 = QtWidgets.QLabel(self.pgpur)
        self.label2.setGeometry(QtCore.QRect(300, 30, 120, 20))
        self.label2.setObjectName("label2")
        self.layoutWidget2 = QtWidgets.QWidget(self.pgpur)
        self.layoutWidget2.setGeometry(QtCore.QRect(150, 80, 360, 120))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout3 = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout3.setContentsMargins(0, 0, 0, 0)
        self.formLayout3.setHorizontalSpacing(30)
        self.formLayout3.setVerticalSpacing(20)
        self.formLayout3.setObjectName("formLayout3")
        self.lbtopur = QtWidgets.QLabel(self.layoutWidget2)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.linebasicbal)
        self.lbtopur.setObjectName("lbtopur")
        self.formLayout3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbtopur)
        self.linepurto = QtWidgets.QLineEdit(self.layoutWidget2)
        self.linepurto.setObjectName("linepurto")
        self.formLayout3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.linepurto)
        self.lb_amount_pur = QtWidgets.QLabel(self.layoutWidget2)
        self.lb_amount_pur.setObjectName("lb_amount_pur")
        self.formLayout3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_amount_pur)
        self.linepuramt = QtWidgets.QLineEdit(self.layoutWidget2)
        self.linepuramt.setObjectName("linepuramt")
        self.formLayout3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.linepuramt)
        self.lbdate_pur = QtWidgets.QLabel(self.layoutWidget2)
        self.lbdate_pur.setObjectName("lbdate_pur")
        self.formLayout3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbdate_pur)
        self.purchase_date = QtWidgets.QDateTimeEdit(self.layoutWidget2)
        self.purchase_date.setReadOnly(False)
        self.purchase_date.setObjectName("purchase_date")
        self.lb_total_b.setObjectName("lb_total_b")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.linebasicborr)
        self.formLayout3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.purchase_date)
        self.layoutWidget3 = QtWidgets.QWidget(self.pgpur)
        self.layoutWidget3.setGeometry(QtCore.QRect(200, 240, 250, 30))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout44 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout44.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout44.setSpacing(100)
        self.horizontalLayout44.setObjectName("horizontalLayout44")
        self.btnsubmitpur = QtWidgets.QPushButton(self.layoutWidget3)
        self.btnsubmitpur.setObjectName("btnsubmitpur")
        self.horizontalLayout44.addWidget(self.btnsubmitpur)
        self.btn_reset_pur = QtWidgets.QPushButton(self.layoutWidget3)
        self.btn_reset_pur.setObjectName("btn_reset_pur")
        self.horizontalLayout44.addWidget(self.btn_reset_pur)
        self.stackedWidget.addWidget(self.pgpur)
        self.pg_borrow = QtWidgets.QWidget()
        self.pg_borrow.setObjectName("pg_borrow")
        self.formLayout2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_trans_from)
        self.lb_to_trans = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_to_trans.setObjectName("lb_to_trans")
        self.formLayout2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_to_trans)
        self.line_trans_to = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_trans_to.setObjectName("line_trans_to")
        self.formLayout2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_trans_to)
        self.label = QtWidgets.QLabel(self.pg_borrow)
        self.label.setGeometry(QtCore.QRect(200, 50, 380, 40))
        self.label.setObjectName("label")
        self.layoutWidget4 = QtWidgets.QWidget(self.pg_borrow)
        self.layoutWidget4.setGeometry(QtCore.QRect(140, 110, 380, 100))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.formLayout4 = QtWidgets.QFormLayout(self.layoutWidget4)
        self.formLayout4.setContentsMargins(0, 0, 0, 0)
        self.formLayout4.setHorizontalSpacing(40)
        self.formLayout4.setVerticalSpacing(30)
        self.formLayout4.setObjectName("formLayout4")
        self.lbamountborrow = QtWidgets.QLabel(self.layoutWidget4)
        self.lbamountborrow.setObjectName("lbamountborrow")
        self.formLayout4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbamountborrow)
        self.lineborramt = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineborramt.setObjectName("lineborramt")
        self.formLayout4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineborramt)
        self.lbdateborrow = QtWidgets.QLabel(self.layoutWidget4)
        self.lbdateborrow.setObjectName("lbdateborrow")
        self.formLayout4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbdateborrow)
        self.borrowing_date = QtWidgets.QDateTimeEdit(self.layoutWidget4)
        self.borrowing_date.setReadOnly(False)
        self.borrowing_date.setObjectName("borrowing_date")
        self.layoutWidget5 = QtWidgets.QWidget(self.pg_borrow)
        self.btnresetbor = QtWidgets.QPushButton(self.layoutWidget5)
        self.btnresetbor.setObjectName("btnresetbor")
        self.horizontalLayout5 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout5.addWidget(self.btnresetbor)
        self.stackedWidget.addWidget(self.pg_borrow)
        self.pg_repay = QtWidgets.QWidget()
        self.pg_repay.setObjectName("pg_repay")
        self.btnokrepay = QtWidgets.QPushButton(self.pg_repay)
        self.btnokrepay.setGeometry(QtCore.QRect(290, 280, 90, 30))
        self.btnokrepay.setObjectName("btnokrepay")
        self.label3 = QtWidgets.QLabel(self.pg_repay)
        self.label3.setGeometry(QtCore.QRect(200, 70, 270, 20))
        self.label3.setObjectName("label3")
        self.layoutWidget5.setGeometry(QtCore.QRect(200, 250, 240, 20))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.table_repay = QtWidgets.QTableWidget(self.pg_repay)
        self.table_repay.setGeometry(QtCore.QRect(80, 100, 520, 140))
        self.table_repay.setObjectName("table_repay")
        self.table_repay.setColumnCount(0)
        self.table_repay.setRowCount(0)
        self.stackedWidget.addWidget(self.pg_repay)
        self.layoutWidget6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(100, 40, 600, 30))
        self.formLayout4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.borrowing_date)
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(30)
        self.btn_borrowing = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_borrowing.setObjectName("btn_borrowing")
        self.horizontalLayout.addWidget(self.btn_borrowing)
        self.btn_repay = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_repay.setObjectName("btn_repay")
        self.horizontalLayout.addWidget(self.btn_repay)
        self.menubar = QtWidgets.QMenuBar(CompanyUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        CompanyUI.setMenuBar(self.menubar)
        self.btn_quit = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_quit.setObjectName("btn_quit")
        self.horizontalLayout.addWidget(self.btn_quit)
        CompanyUI.setCentralWidget(self.centralwidget)
        self.btn_info = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_info.setObjectName("btn_info")
        self.horizontalLayout.addWidget(self.btn_info)
        self.btn_transfer = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_transfer.setObjectName("btn_transfer")
        self.horizontalLayout.addWidget(self.btn_transfer)
        self.btn_purchasing = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_purchasing.setObjectName("btn_purchasing")
        self.horizontalLayout5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout5.setSpacing(80)
        self.horizontalLayout5.setObjectName("horizontalLayout5")
        self.btnsubmitbor = QtWidgets.QPushButton(self.layoutWidget5)
        self.btnsubmitbor.setObjectName("btnsubmitbor")
        self.horizontalLayout5.addWidget(self.btnsubmitbor)
        self.horizontalLayout.addWidget(self.btn_purchasing)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statusbar = QtWidgets.QStatusBar(CompanyUI)
        self.statusbar.setObjectName("statusbar")
        CompanyUI.setStatusBar(self.statusbar)

        self.retranslateUi(CompanyUI)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(CompanyUI)

    def retranslateUi(self, CompanyUI):
        _translate = QtCore.QCoreApplication.translate
        CompanyUI.setWindowTitle(_translate("CompanyUI", "Window"))
        self.lbdate.setText(_translate("CompanyUI", "Date"))
        self.lb_balance.setText(_translate("CompanyUI", "Balance"))
        self.lb_from_trans.setText(_translate("CompanyUI", "From"))
        self.lb_to_trans.setText(_translate("CompanyUI", "To"))
        self.btnsubmittrans.setText(_translate("CompanyUI", "Enter"))
        self.btnresettrans.setText(_translate("CompanyUI", "Reset"))
        self.lbborrowedtrans.setText(_translate("CompanyUI", "Lent List"))
        self.btn_reset_pur.setText(_translate("CompanyUI", "Reset"))
        self.btn_info.setText(_translate("CompanyUI", "Basic Info"))
        self.btn_transfer.setText(_translate("CompanyUI", "Transfer"))
        self.btn_purchasing.setText(_translate("CompanyUI", "Purchasing"))
        self.btn_borrowing.setText(_translate("CompanyUI", "Borrowing"))
        self.lb_total_b.setText(_translate("CompanyUI", "Total borrowed"))
        self.lbtotall.setText(_translate("CompanyUI", "Total lent"))
        self.lb_borrowed.setText(_translate("CompanyUI", "borrowed"))
        self.lblent.setText(_translate("CompanyUI", "lent"))
        self.label.setText(_translate("CompanyUI", "borrowing from bank"))
        self.btnsubmitbor.setText(_translate("CompanyUI", "Enter"))
        self.lbamounttrans.setText(_translate("CompanyUI", "Amount"))
        self.btnresetbor.setText(_translate("CompanyUI", "Reset"))
        self.btnokrepay.setText(_translate("CompanyUI", "Enter"))
        self.lbamountborrow.setText(_translate("CompanyUI", "Amount"))
        self.lbdatetrans.setText(_translate("CompanyUI", "Due Date"))
        self.label2.setText(_translate("CompanyUI", "Purchasing Form"))
        self.lbtopur.setText(_translate("CompanyUI", "To"))
        self.lb_amount_pur.setText(_translate("CompanyUI", "Amount"))
        self.lbdate_pur.setText(_translate("CompanyUI", "Due Date"))
        self.btnsubmitpur.setText(_translate("CompanyUI", "Enter"))
        self.lbdateborrow.setText(_translate("CompanyUI", "Due date"))
        self.label3.setText(_translate("CompanyUI", "Click to select"))
        self.btn_repay.setText(_translate("CompanyUI", "Repaying"))
        self.btn_quit.setText(_translate("CompanyUI", "Close"))
